### ISSUE TITLE
See also "FxCop rules implemented with Roslyn analyzers on GitHub" not available

### ISSUE THREAD

**Issue by DanielHWe** [MicrosoftDocs/visualstudio-docs.de-de#33]
Link https://github.com/dotnet/roslyn/tree/master/src/Diagnostics/FxCop is no more available

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3c7753cc-f0b0-a3a3-1531-0a1eb6d62d06
* Version Independent ID: a465dccd-6d42-f88a-feee-1dc7aa707f96
* Content: [Erste Schritte mit Roslyn-Analysetools - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2017)
* Content Source: [docs/extensibility/getting-started-with-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/extensibility/getting-started-with-roslyn-analyzers.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #2158](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2158) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DanielHWe 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/2158.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
