### ISSUE TITLE
add new exolenation is outdated

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/visualstudio-docs.de-de#75]
hi. this seems to be outdated:  `"In the Solution Explorer, right-click the project node and select Add &gt; New Item. Go to the Visual C# Extensibility node and select Editor Classifier. Leave the default file name (EditorClassifier1.cs)."`

it is possible to add a new `Editor Classifier` with `Add =&gt; Component =&gt; then search for "Editor Classifier"`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1d3619ee-c26c-770f-595e-f3932b4852b0
* Version Independent ID: 677edcd7-7893-369d-0e06-11a56b05eff5
* Content: [Erstellen einer Erweiterung mit einer Editor-Elementvorlage - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/extensibility/creating-an-extension-with-an-editor-item-template?view=vs-2019)
* Content Source: [docs/extensibility/creating-an-extension-with-an-editor-item-template.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/extensibility/creating-an-extension-with-an-editor-item-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by srvbpigh** [comment]
Hello, @BrayanKhosravian
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @BrayanKhosravian, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4509. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
