### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by EnemyArea** [MicrosoftDocs/visualstudio-docs.de-de#83]
https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/javascript/tutorial-aspnet-with-typescript.md

The typescript output-path is wrong. It should be 
"outDir": "wwwroot/js"
instead of "outDir": "../wwwroot/js"

The path in "exclude" gives the hint :)

**Comment by srvbpigh** [comment]
Hello, @EnemyArea
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #5214](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5214) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @EnemyArea 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5214

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @EnemyArea, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5214. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
